# Generated by Django 5.1 on 2024-09-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
